Yahhh
UCL-MPHY0021-21-22/Travel-guide pull request #24
Opened 2021-10-21 11:45 UTC by Timlllllli

2021-10-21 14:33 UTC, dpshelio requested changes
Great contribution! Thanks.

A couple of things to keep an eye for:
- commit messages need to be descriptive
- Pull request title should be meaningful, something like the location you are adding is preferred.

Please, follow the suggestions underr this review so that we can merge your contribution!

2021-10-21 14:33 UTC, dpshelio commented on README.md
> +
These changes are not needed. Or at least requires an explanation to explain why a change of name is suggested :wink:

2021-10-21 14:33 UTC, dpshelio commented on README.md
> + - [Shanxi](https://github.com/Timlllllli/Travel-guide/blob/yahhh/asia/china/Shanxi.md)
This link is not required. Its content is already under the contribution to this repository.

2021-10-21 14:33 UTC, dpshelio commented on asia/china/Shanxi.md
> +- [README](./README.md)
This link points to China's readme, so it's better to add a more descriptive name to this link :wink: 
```suggestion
- [China](./README.md)
```

2021-10-22 02:13 UTC, zwei21 reviewed
A cluster  of dir is required, for example, the internal link should be held for the following structures:
Link1:Asia/README->China/README
Link2:China/README->Shanxi.md
Other descriptions and internal links is not required in the issue.

2021-10-22 02:14 UTC, closed without merging